kind = "web"
previewPath = "/"
title = "Fitest"
version = "1.0.0"
id = "artifacts/fitest"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24435

[services.development]
run = "pnpm --filter @workspace/fitest run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fitest", "run", "build" ]
publicDir = "artifacts/fitest/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24435"
BASE_PATH = "/"
